version: '3'
services:
  elasticsearch1:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.1
    container_name: elasticsearch1
    environment:
      - "discovery.type=single-node"
    deploy:
        resources:
            limits:
                memory: "0.4g"
    volumes:
      - esdata1:/usr/share/elasticsearch/data:rw
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk
    restart: unless-stopped
  kibana1:
    depends_on:
    - elasticsearch1
    image: docker.elastic.co/kibana/kibana:7.13.1
    networks:
      - elk
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch1:9200
    deploy:
      resources:
          limits:
              memory: "0.4g"
    restart: unless-stopped
volumes:
    esdata1:
        driver: local
networks:
    elk: