/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

/* INSPECTION */
export const INSPECTION_LIST = 'INSPECTION_LIST';
export const INSPECTION_LIST_SUCCESS = 'INSPECTION_LIST_SUCCESS';
export const INSPECTION_LIST_ERROR = 'INSPECTION_LIST_ERROR';