/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";

/* INSPECTION */
export const INSPECTION_LIST = 'INSPECTION_LIST';
export const INSPECTION_LIST_SUCCESS = 'INSPECTION_LIST_SUCCESS';
export const INSPECTION_LIST_ERROR = 'INSPECTION_LIST_ERROR';

export const INSPECTION_ADD = 'INSPECTION_ADD';
export const INSPECTION_ADD_SUCCESS = 'INSPECTION_ADD_SUCCESS';
export const INSPECTION_ADD_ERROR = 'INSPECTION_ADD_ERROR';

export const INSPECTION_UPDATE = 'INSPECTION_UPDATE';
export const INSPECTION_UPDATE_SUCCESS = 'INSPECTION_UPDATE_SUCCESS';
export const INSPECTION_UPDATE_ERROR = 'INSPECTION_UPDATE_ERROR';

export const INSPECTION_DETAIL = 'INSPECTION_DETAIL';
export const INSPECTION_DETAIL_SUCCESS = 'INSPECTION_DETAIL_SUCCESS';
export const INSPECTION_DETAIL_ERROR = 'INSPECTION_DETAIL_ERROR';
